### ISSUE TITLE
 Object of type 'datetime' is not JSON serializable

### ISSUE THREAD

**Issue by kigsmtua** [Trax-air/swagger-parser#50]
unable to parse valid file with error Object of type 'datetime' is not JSON serializable

**Comment by flavianh** [comment]
@kigsmtua Can you give us steps to reproduce your issue?

**Comment by kigsmtua** [comment]
@flavianh  when the swagger yaml file has a definition with the u.t.c format as I will show below is when the error actually occurs.  

Steps to reproduce:
Use the swagger parser to parse a valid yaml with the datetime field in the definitions as below:
 
```yaml
"releaseDate": {
          "type": "string",
          "format": "int32",
          "example": "2016-08-29T09:12:33.001Z"
  },
```
My digging shows thats its because of how pyaml understands such a format. While parsing it will give an instance of the datetime object which swagger validator library seems not to understand
on 
[https://github.com/Trax-air/swagger-parser/blob/master/swagger_parser/swagger_parser.py#L59](url)

when yaml.load is called it returns that field as below .

```yaml
datetime.datetime(2016, 8, 29, 9, 12, 33, 1000)
```
 
I would glad to pull a pr if you can guide on how we can go about this
