### ISSUE TITLE
not validating properties

### ISSUE THREAD

**Issue by markfink** [Trax-air/swagger-parser#55]
relevant part of the spec:
``` yaml
   properties:
      ...
      artifactBucket:
        type: string
        minLength: 5
        pattern: "arn:aws:([a-zA-Z0-9-])+:([a-z]{2}-[a-z]+-d{1})?:(d{12})?:(.*)"
        example: bla
```

this is how I use `validate_request`:
``` python
my_config = {
    "stack": {
        "StackName": "infra-dev-kumo-sample-stack",
        "RoleARN": "arn:aws:iam::<AccountID>:role/<CloudFormationRoleName>",
        "artifactBucket": "bla",
        "NotificationARNs": [
            "arn:aws:sns:eu-west-1:123456789012:mytopic2"
        ]
    }
}

print(parser.validate_request('/kumo', 'get', body=my_config))
```

if I run this I get:
``` bash
$ python config_validate_kumo.py
True
```

I would expect `False` with an error message that explains the problem with `artifactBucket`.
